### ISSUE TITLE
Game doesn't finish when bike hits de border

### ISSUE THREAD

**Issue by RodolfovMoreira** [andrewnitu/LightBike#7]
When the bike reaches the border an "Game Over" is not launched.
Develop the 'GameOverView' for when the bike hit, the game ends.

**Comment by andrewnitu** [comment]
Will be done soon :)

**Comment by andrewnitu** [comment]
Hey, I just wanted to say, thanks for deciding to contribute! I honestly never expected someone would so I didn't set up comments, documentation, etc... I will begin to do that now :)

Let's finish this cool game together :)

**Comment by andrewnitu** [comment]
Functionality added
